# Generated by Django 5.0.14 on 2025-06-11 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_detalleventa_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
